name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  license:
    name: Check License Header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes/header@main #NOSONAR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: .licenserc.yaml
          mode: check

  CI:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - '1.25'
        os:
          - ubuntu-latest

    steps:

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Cache Go Dependence
      # ref: https://github.com/actions/cache/blob/main/examples.md#go---module
      uses: actions/cache@v4
      with:
        # Cache, works only on Linux
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: ${{ runner.os }}-go-

    - name: Check Code Format
      run: make fmt && git status && [[ -z `git status -s` ]]

    - name: Unit Test
      run: make test

    - name: Lint
      run: make lint

    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)
